local emerge = require("emerge")

describe("emerge.tracker", function()
    it("completes when the last callback arrives", function()
        local t = emerge.tracker()
        assert.is_nil(t:step("ok", 2))
        assert.is_nil(t:step("ok", 1))
        local r = t:step("ok", 0)
        assert.is_table(r)
        assert.is_true(r.ok)
        assert.are.equal(3, r.blocks)
    end)

    it("completes on a single-block emerge", function()
        local t = emerge.tracker()
        local r = t:step("ok", 0)
        assert.is_true(r.ok)
        assert.are.equal(1, r.blocks)
    end)

    -- An error part way through must not resolve early: emerge_area keeps
    -- calling back for the remaining blocks, and resolving twice would run the
    -- job's continuation twice.
    it("waits for the final callback even after an error", function()
        local t = emerge.tracker()
        assert.is_nil(t:step("errored", 2))
        assert.is_nil(t:step("ok", 1))
        local r = t:step("ok", 0)
        assert.is_false(r.ok)
        assert.are.equal(1, r.errored)
        assert.is_string(r.error)
    end)

    it("fails when the error is itself the last callback", function()
        local t = emerge.tracker()
        assert.is_nil(t:step("ok", 1))
        local r = t:step("errored", 0)
        assert.is_false(r.ok)
        assert.are.equal(1, r.errored)
    end)

    it("fails on cancellation", function()
        local t = emerge.tracker()
        local r = t:step("cancelled", 0)
        assert.is_false(r.ok)
        assert.are.equal(1, r.cancelled)
    end)

    it("counts errors and cancellations separately", function()
        local t = emerge.tracker()
        t:step("errored", 3)
        t:step("cancelled", 2)
        t:step("errored", 1)
        local r = t:step("ok", 0)
        assert.is_false(r.ok)
        assert.are.equal(2, r.errored)
        assert.are.equal(1, r.cancelled)
        assert.are.equal(4, r.blocks)
    end)

    it("resolves exactly once", function()
        local t = emerge.tracker()
        assert.is_table(t:step("ok", 0))
        assert.is_nil(t:step("ok", 0))
    end)
end)
